---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure PostgreSQL service is enabled and started
  service:
    name: postgresql
    state: started
    enabled: true
