---
- name: Configure master server
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/13/main/postgresql.conf
  notify: restart postgresql

- name: Configure pg_hba.conf for replication
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/13/main/pg_hba.conf
  notify: restart postgresql

- name: Create replication user
  postgresql_user:
    name: replicator
    password: my_secure_password
    role_attr_flags: REPLICATION

- name: Allow replication connections
  lineinfile:
    dest: /etc/postgresql/13/main/pg_hba.conf
    line: "host replication replicator {{ slave_ip }}/32 md5"
    state: present
  notify: restart postgresql
